const props=window.VJTF_PROPS;
const mapStage=document.getElementById('mapStage'),details=document.getElementById('details'),cards=document.getElementById('cards'),galleryGrid=document.getElementById('galleryGrid'),search=document.getElementById('search'),filters=document.getElementById('filters'),visibleCount=document.getElementById('visibleCount'),tooltip=document.getElementById('mapTooltip');
let category='All',query='';
const cats=['All',...new Set(props.map(p=>p.category))];
cats.forEach(c=>{const b=document.createElement('button');b.textContent=c;b.className=c==='All'?'active':'';b.onclick=()=>{category=c;[...filters.children].forEach(x=>x.classList.toggle('active',x===b));render()};filters.appendChild(b)});
function matches(p){const q=query.trim().toLowerCase();return (category==='All'||p.category===category)&&(!q||[p.letter,p.name,p.category,p.description,...p.training].join(' ').toLowerCase().includes(q))}
function hero(p){return p.photos?.[0]||''}
function showTooltip(p,el){const image=hero(p);tooltip.innerHTML=`${image?`<img src="${image}" alt="">`:`<div class="tooltip-fallback">${p.letter}</div>`}<div><span>${p.category}</span><strong>${p.letter} · ${p.name}</strong><small>Click for details</small></div>`;tooltip.classList.add('show');positionTooltip(el)}
function positionTooltip(el){const r=el.getBoundingClientRect(),w=tooltip.offsetWidth||260,h=tooltip.offsetHeight||100;let left=r.right+12,top=r.top+r.height/2-h/2;if(left+w>innerWidth-12)left=r.left-w-12;if(top<12)top=12;if(top+h>innerHeight-12)top=innerHeight-h-12;tooltip.style.left=left+'px';tooltip.style.top=top+'px'}
function hideTooltip(){tooltip.classList.remove('show')}
function makeHotspots(){props.filter(p=>p.mapHotspot&&p.letter).forEach(p=>{const b=document.createElement('button');b.className='hotspot';b.dataset.id=p.id;b.dataset.letter=p.letter;if(['I','J','L','M'].includes(p.letter)){b.classList.add('restored-label');b.innerHTML=`<svg viewBox="0 0 24 24" width="100%" height="100%" aria-hidden="true"><rect x="0.6" y="0.6" width="22.8" height="22.8" fill="#fff" stroke="#343434" stroke-width="1.2"/><text x="12" y="19.4" text-anchor="middle" fill="#111" font-family="Arial, sans-serif" font-weight="700" font-size="22">${p.letter}</text></svg>`;}Object.assign(b.style,{left:p.left+'%',top:p.top+'%',width:p.width+'%',height:p.height+'%'});b.setAttribute('aria-label',`${p.letter}: ${p.name}`);b.onmouseenter=()=>showTooltip(p,b);b.onmouseleave=hideTooltip;b.onfocus=()=>showTooltip(p,b);b.onblur=hideTooltip;b.onclick=()=>{hideTooltip();selectProp(p)};mapStage.appendChild(b)})}
function selectProp(p){document.querySelectorAll('.hotspot').forEach(h=>h.classList.toggle('active',h.dataset.id===p.id));const photos=p.photos||[];details.innerHTML=`<div class="detail-hero">${hero(p)?`<img src="${hero(p)}" alt="${p.name}">`:`<div class="fallback">${p.letter||'HFD'}</div>`}<div class="detail-overlay"><span class="badge">${p.category}</span><h2>${p.letter?`${p.letter} · `:''}${p.name}</h2></div></div><div class="detail-body"><p>${p.description}</p><h3>Training capabilities</h3><div class="chips">${p.training.map(t=>`<span class="chip">${t}</span>`).join('')}</div><h3>Photo gallery ${photos.length?`(${photos.length})`:''}</h3>${photos.length?`<div class="thumbs">${photos.map(x=>`<img src="${x}" alt="${p.name}" data-full="${x}">`).join('')}</div>`:`<p>Additional photographs can be added during the next content update.</p>`}</div>`;details.querySelectorAll('[data-full]').forEach(i=>i.onclick=()=>openLightbox(i.dataset.full));if(innerWidth<1000)details.scrollIntoView({behavior:'smooth',block:'start'})}
function render(){const list=props.filter(matches);visibleCount.textContent=list.filter(p=>p.mapHotspot).length;document.querySelectorAll('.hotspot').forEach(h=>{const p=props.find(x=>x.id===h.dataset.id);h.hidden=!list.includes(p)});cards.innerHTML=list.map(p=>`<article class="card" data-id="${p.id}"><div class="card-img">${hero(p)?`<img src="${hero(p)}" alt="${p.name}">`:(p.letter||'HFD')}</div><div class="card-body"><span class="badge">${p.category}</span><h3>${p.letter?`${p.letter} · `:''}${p.name}</h3><p>${p.training.slice(0,3).join(' • ')}</p></div></article>`).join('');cards.querySelectorAll('.card').forEach(c=>c.onclick=()=>{showView('map');selectProp(props.find(p=>p.id===c.dataset.id))});galleryGrid.innerHTML=list.flatMap(p=>(p.photos||[]).map(x=>`<figure class="gallery-item"><img src="${x}" alt="${p.name}" data-full="${x}"><div>${p.letter?`${p.letter} · `:''}${p.name}</div></figure>`)).join('')||'<p>No photographs match the current filter.</p>';galleryGrid.querySelectorAll('[data-full]').forEach(i=>i.onclick=()=>openLightbox(i.dataset.full))}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));hideTooltip()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showView(b.dataset.view));search.oninput=e=>{query=e.target.value;render()};document.getElementById('reset').onclick=()=>{query='';category='All';search.value='';[...filters.children].forEach((x,i)=>x.classList.toggle('active',i===0));render()};
const lb=document.getElementById('lightbox'),lbi=document.getElementById('lightboxImg');function openLightbox(src){lbi.src=src;lb.classList.add('open')}document.getElementById('closeLightbox').onclick=()=>lb.classList.remove('open');lb.onclick=e=>{if(e.target===lb)lb.classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){lb.classList.remove('open');hideTooltip()}});window.addEventListener('resize',hideTooltip);window.addEventListener('scroll',hideTooltip,true);
makeHotspots();render();
